default: &default
  adapter: mysql2
  database: simple_rails_crud_app
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8

development:
  <<: *default
  database: simple_rails_crud_app

test:
  <<: *default
  database: simple_rails_crud_app_test

production:
  <<: *default
  database: simple_rails_crud_app
